pipeline {

  environment {
    imageStream = "default-route-openshift-image-registry/va/jenkins-test"
    registryCredential = 'ocp-registry'
    dockerImage = ''
  }

  agent any
  stages {
      stage('Cloning Git') {
        steps {
            git 'https://github.com/vivin12/test-app' //Replace with SVN repository
        }
    }

    stage('Building image') {
      steps {
        script {
          dockerImage = docker.build imageStream + ":$BUILD_NUMBER"
        }
      }
    }

    stage('Deploy Image') {
      steps {
        script {
          docker.withRegistry( 'http://default-route-openshift-image-registry/va/jenkins-test', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }

    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }

}

